version: "3"
services: 
    nginx:
        ports: 
        - "80:80"

    node-docker-app:
        build:
            context: .
            args: 
                NODE_ENV: production
        environment: 
            - NODE_ENV=production
            - MONGO_USER=admin
            - MONGO_PASS=admin
            - SESSION_SECRET=secret
        command: npm run start