version: "3"
services: 
    nginx:
        image: nginx:stable-alpine
        volumes: 
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on: 
            - node-docker-app
    node-docker-app:
        build: .
        environment: 
            - PORT=4000
        # this will indicate at start time that this service depends on "mongo" service and to boot up that container
        # first before booting up this
        depends_on: 
            - mongo
    
    # if you're not building a custom docker image, you can use "image" attribute to pull the base image
    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
        volumes: 
            - mongo-db:/data/db

    redis:
        image: redis

# adding this attribute to define the name of the volume to be used
# in named volumes. you can use the same name in many services
# but it will have all the data of the services used by it
volumes: 
    mongo-db: