version: "3"
services: 
    nginx: 
        ports: 
            - "3000:80"

    node-docker-app:
        build:
            context: .
            args: 
                NODE_ENV: development
        volumes: 
            - ./:/app
            - /app/node_modules
        environment: 
            - NODE_ENV=development
            - MONGO_USER=admin
            - MONGO_PASS=admin
            - SESSION_SECRET=secret
        command: npm run dev